use_frameworks!

platform :ios, '9.0'
source 'https://github.com/Yamyee/Spces'
source 'https://github.com/cocoapods/Specs'
target 'yybase_Example' do
  pod 'yybase', :path => '../'

  target 'yybase_Tests' do
    inherit! :search_paths

    
  end
end
